[package]
name = "capit"
version = "0.1.0"
edition = "2024"

[dependencies]
capit-core = { path = "../capit-core", features = ["clap"] }
capit-ipc  = { path = "../capit-ipc" }

clap = { version = "4.5.58", features = ["derive"] }
eventline = "0.6.1"
