[package]
name = "capit-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
capit-core = { path = "../capit-core" }
serde = { version = "1.0.228", features = ["derive"] }
postcard = { version = "1.1.3", features = ["alloc"] }
thiserror = "2.0.18"
